/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

/**
 *
 * @author Ryan
 */
import javax.swing.*;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.JScrollPane;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.BorderFactory;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.Color;
import java.awt.Font;
import ProcessQueue.*;
import Schedulers.*;
public class FCFSJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FCFSJFrame.class.getName());
    
    private HoldQueue hold = new HoldQueue();
    private FirstComeFirstServed fcfs;
    private ShortestJobNext sjn;
    private RoundRobin rr;

    /**
     * Creates new form FCFSJFrame
     */
    public FCFSJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        config = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        processName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        burstTime = new javax.swing.JTextField();
        arrivalTime = new javax.swing.JTextField();
        insert = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        fcfsbtn = new javax.swing.JButton();
        sjnbtn = new javax.swing.JButton();
        rrbtn = new javax.swing.JButton();
        output = new javax.swing.JPanel();
        dynamicOutput = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        config.setBorder(javax.swing.BorderFactory.createTitledBorder("Process Configuration"));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Add Process");

        jLabel2.setText("Proces Name:");

        jLabel3.setText("Arrival Time:");

        jLabel4.setText("Burst Time:");

        arrivalTime.addActionListener(this::arrivalTimeActionPerformed);

        insert.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        insert.setText("Insert");
        insert.addActionListener(this::insertActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Solve With");

        fcfsbtn.setText("First Come First Served");
        fcfsbtn.addActionListener(this::fcfsbtnActionPerformed);

        sjnbtn.setText("Shortest Job Next");
        sjnbtn.addActionListener(this::sjnbtnActionPerformed);

        rrbtn.setText("Round Robin");
        rrbtn.addActionListener(this::rrbtnActionPerformed);

        javax.swing.GroupLayout configLayout = new javax.swing.GroupLayout(config);
        config.setLayout(configLayout);
        configLayout.setHorizontalGroup(
            configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fcfsbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(insert, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(arrivalTime, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(processName)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(burstTime, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sjnbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(rrbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        configLayout.setVerticalGroup(
            configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(processName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(arrivalTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(burstTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(insert, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(fcfsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sjnbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rrbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        output.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));

        javax.swing.GroupLayout outputLayout = new javax.swing.GroupLayout(output);
        output.setLayout(outputLayout);
        outputLayout.setHorizontalGroup(
            outputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dynamicOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE))
        );
        outputLayout.setVerticalGroup(
            outputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputLayout.createSequentialGroup()
                .addComponent(dynamicOutput)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(config, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(output, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(output, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(config, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void arrivalTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrivalTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrivalTimeActionPerformed

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        // TODO add your handling code here:
        try{
            String pName = processName.getText();
            int aTime = Integer.parseInt(arrivalTime.getText());
            int bTime = Integer.parseInt(burstTime.getText());
            
            ProcessControlBlock p = new ProcessControlBlock(
                    pName,
                    aTime,
                    bTime
            );
            
            hold.enqueue(p);
            
            processName.setText("");
            arrivalTime.setText("");
            burstTime.setText("");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter a valid input!");
        }
    }//GEN-LAST:event_insertActionPerformed

    private void fcfsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcfsbtnActionPerformed
        // TODO add your handling code here:
        fcfs = new FirstComeFirstServed();
        fcfs.schedule(hold);

        FinishedQueue finishedProcesses = fcfs.getFinishedProcesses();
        GanttChart[] ganttChart = fcfs.getGanttChart();

        String[] columns = {
            "Process Name",
            "Arrival Time",
            "Burst Time",
            "Start Time",
            "Waiting Time"
        };

        DefaultTableModel model = new DefaultTableModel(columns, 0);
        JTable table = new JTable(model);

        int numProcess = finishedProcesses.getSize();
        for(int i=0; i<numProcess; i++){
            ProcessControlBlock process = finishedProcesses.dequeue();

            model.addRow(new Object[]{
                process.getProcessName(),
                process.getArrivalTime(),
                process.getBurstTime(),
                process.getStartTime(),
                process.getWaitingTime()
            });
            
            finishedProcesses.enqueue(process);
        }
        
        JLabel method = new JLabel();
        method.setText("First Come First Served");
        method.setFont(new Font("Arial", Font.PLAIN, 18));

        JPanel ganttPanel = new JPanel(new GridLayout(1, 0, 0, 0));

        for(GanttChart entry : ganttChart){
            if (entry == null) {
                break;
            }

            JLabel cell = new JLabel(
                    entry.getProcessName(),
                    SwingConstants.CENTER
            );
            cell.setBorder(
                    BorderFactory.createLineBorder(Color.BLACK)
            );

            ganttPanel.add(cell);
        }

        JPanel dynamicOutput = new JPanel();
        dynamicOutput.setLayout(new BorderLayout());
        
        dynamicOutput.add(
                method,
                BorderLayout.NORTH
        );

        dynamicOutput.add(
                new JScrollPane(table),
                BorderLayout.CENTER
        );

        dynamicOutput.add(
                new JScrollPane(
                        ganttPanel,
                        JScrollPane.VERTICAL_SCROLLBAR_NEVER,
                        JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED
                ),
                BorderLayout.SOUTH
        );

        output.removeAll();

        output.setLayout(new BorderLayout());

        output.add(
                new JScrollPane(dynamicOutput),
                BorderLayout.CENTER
        );

        output.revalidate();
        output.repaint();
    }//GEN-LAST:event_fcfsbtnActionPerformed

    private void sjnbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sjnbtnActionPerformed
        // TODO add your handling code here:
        sjn = new ShortestJobNext();
        sjn.schedule(hold);
        
        FinishedQueue finishedProcesses = sjn.getFinishedProcesses();
        GanttChart[] ganttChart = sjn.getGanttChart();

        String[] columns = {
            "Process Name",
            "Arrival Time",
            "Burst Time",
            "Start Time",
            "Waiting Time"
        };

        DefaultTableModel model = new DefaultTableModel(columns, 0);
        JTable table = new JTable(model);

        int numProcess = finishedProcesses.getSize();
        for(int i=0; i<numProcess; i++){
            ProcessControlBlock process = finishedProcesses.dequeue();

            model.addRow(new Object[]{
                process.getProcessName(),
                process.getArrivalTime(),
                process.getBurstTime(),
                process.getStartTime(),
                process.getWaitingTime()
            });
            
            finishedProcesses.enqueue(process);
        }
        
        JLabel method = new JLabel();
        method.setText("Shortest Job Next");
        method.setFont(new Font("Arial", Font.PLAIN, 18));

        JPanel ganttPanel = new JPanel(new GridLayout(1, 0, 0, 0));

        for(GanttChart entry : ganttChart){
            if (entry == null) {
                break;
            }

            JLabel cell = new JLabel(
                    entry.getProcessName(),
                    SwingConstants.CENTER
            );
            cell.setBorder(
                    BorderFactory.createLineBorder(Color.BLACK)
            );

            ganttPanel.add(cell);
        }

        JPanel dynamicOutput = new JPanel();
        dynamicOutput.setLayout(new BorderLayout());
        
        dynamicOutput.add(
                method,
                BorderLayout.NORTH
        );

        dynamicOutput.add(
                new JScrollPane(table),
                BorderLayout.CENTER
        );

        dynamicOutput.add(
                new JScrollPane(
                        ganttPanel,
                        JScrollPane.VERTICAL_SCROLLBAR_NEVER,
                        JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED
                ),
                BorderLayout.SOUTH
        );

        output.removeAll();

        output.setLayout(new BorderLayout());

        output.add(
                new JScrollPane(dynamicOutput),
                BorderLayout.CENTER
        );

        output.revalidate();
        output.repaint();
    }//GEN-LAST:event_sjnbtnActionPerformed

    private void rrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rrbtnActionPerformed
        // TODO add your handling code here:
        try{
            int tq = Integer.parseInt(JOptionPane.showInputDialog("Enter time quantum"));
            rr = new RoundRobin(tq);
            rr.schedule(hold);
            
            FinishedQueue finishedProcesses = rr.getFinishedProcesses();
        GanttChart[] ganttChart = rr.getGanttChart();

        String[] columns = {
            "Process Name",
            "Arrival Time",
            "Burst Time",
            "Completion Time",
            "Turn Around Time",
            "Waiting Time"
        };

        DefaultTableModel model = new DefaultTableModel(columns, 0);
        JTable table = new JTable(model);

        int numProcess = finishedProcesses.getSize();
        for(int i=0; i<numProcess; i++){
            ProcessControlBlock process = finishedProcesses.dequeue();

            model.addRow(new Object[]{
                process.getProcessName(),
                process.getArrivalTime(),
                process.getBurstTime(),
                process.getCompletionTime(),
                process.getTurnAroundTime(),
                process.getWaitingTime()
            });
            
            finishedProcesses.enqueue(process);
        }
        
        JLabel method = new JLabel();
        method.setText("Round Robin");
        method.setFont(new Font("Arial", Font.PLAIN, 18));

        JPanel ganttPanel = new JPanel(new GridLayout(1, 0, 0, 0));

        for(GanttChart entry : ganttChart){
            if (entry == null) {
                break;
            }

            JLabel cell = new JLabel(
                    entry.getProcessName(),
                    SwingConstants.CENTER
            );
            cell.setBorder(
                    BorderFactory.createLineBorder(Color.BLACK)
            );

            ganttPanel.add(cell);
        }

        JPanel dynamicOutput = new JPanel();
        dynamicOutput.setLayout(new BorderLayout());
        
        dynamicOutput.add(
                method,
                BorderLayout.NORTH
        );

        dynamicOutput.add(
                new JScrollPane(table),
                BorderLayout.CENTER
        );

        dynamicOutput.add(
                new JScrollPane(
                        ganttPanel,
                        JScrollPane.VERTICAL_SCROLLBAR_NEVER,
                        JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED
                ),
                BorderLayout.SOUTH
        );

        output.removeAll();

        output.setLayout(new BorderLayout());

        output.add(
                new JScrollPane(dynamicOutput),
                BorderLayout.CENTER
        );

        output.revalidate();
        output.repaint();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter a valid time quntum!");
        }
    }//GEN-LAST:event_rrbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (processNameuals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FCFSJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arrivalTime;
    private javax.swing.JTextField burstTime;
    private javax.swing.JPanel config;
    private javax.swing.JScrollPane dynamicOutput;
    private javax.swing.JButton fcfsbtn;
    private javax.swing.JButton insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel output;
    private javax.swing.JTextField processName;
    private javax.swing.JButton rrbtn;
    private javax.swing.JButton sjnbtn;
    // End of variables declaration//GEN-END:variables
}
