/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

/**
 *
 * @author Ryan
 */
import javax.swing.*;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.JScrollPane;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.BorderFactory;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Dimension;
import ProcessQueue.*;
import Schedulers.*;
public class MainScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainScreen.class.getName());
    
    private HoldQueue hold = new HoldQueue();
    private FirstComeFirstServed fcfs;
    private ShortestJobNext sjn;
    private RoundRobin rr;
    private DefaultTableModel tableModel;
    private JTable tableForInput;
    /**
     * Creates new form FCFSJFrame
     */
    public MainScreen() {
        initComponents();
        
        String[] columns = {
                "Process Name",
                "Arrival Time",
                "Burst Time"
            };
        tableModel = new DefaultTableModel(columns, 0);
        tableForInput = new JTable(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        config = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        processName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        burstTime = new javax.swing.JTextField();
        arrivalTime = new javax.swing.JTextField();
        insert = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        fcfsbtn = new javax.swing.JButton();
        sjnbtn = new javax.swing.JButton();
        rrbtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        restart = new javax.swing.JButton();
        terminate = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        output = new javax.swing.JPanel();
        dynamicOutput = new javax.swing.JScrollPane();
        input = new javax.swing.JPanel();
        dynamicInput = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        config.setBorder(javax.swing.BorderFactory.createTitledBorder("Process Configuration"));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Add Process");

        jLabel2.setText("Proces Name:");

        jLabel3.setText("Arrival Time:");

        jLabel4.setText("Burst Time:");

        arrivalTime.addActionListener(this::arrivalTimeActionPerformed);

        insert.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        insert.setText("Add");
        insert.addActionListener(this::insertActionPerformed);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Schedule With");

        fcfsbtn.setText("First Come First Served");
        fcfsbtn.addActionListener(this::fcfsbtnActionPerformed);

        sjnbtn.setText("Shortest Job Next");
        sjnbtn.addActionListener(this::sjnbtnActionPerformed);

        rrbtn.setText("Round Robin");
        rrbtn.addActionListener(this::rrbtnActionPerformed);

        restart.setText("Restart");
        restart.addActionListener(this::restartActionPerformed);

        terminate.setText("End Program");
        terminate.addActionListener(this::terminateActionPerformed);

        javax.swing.GroupLayout configLayout = new javax.swing.GroupLayout(config);
        config.setLayout(configLayout);
        configLayout.setHorizontalGroup(
            configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(configLayout.createSequentialGroup()
                        .addGroup(configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(restart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fcfsbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(insert, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(arrivalTime, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(processName)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(burstTime, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sjnbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(rrbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(terminate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        configLayout.setVerticalGroup(
            configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(processName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(arrivalTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(burstTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(insert, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(restart, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fcfsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(sjnbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rrbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(terminate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        output.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));

        javax.swing.GroupLayout outputLayout = new javax.swing.GroupLayout(output);
        output.setLayout(outputLayout);
        outputLayout.setHorizontalGroup(
            outputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dynamicOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                .addContainerGap())
        );
        outputLayout.setVerticalGroup(
            outputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, outputLayout.createSequentialGroup()
                .addComponent(dynamicOutput)
                .addContainerGap())
        );

        input.setBorder(javax.swing.BorderFactory.createTitledBorder("Input"));

        javax.swing.GroupLayout inputLayout = new javax.swing.GroupLayout(input);
        input.setLayout(inputLayout);
        inputLayout.setHorizontalGroup(
            inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dynamicInput)
                .addContainerGap())
        );
        inputLayout.setVerticalGroup(
            inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputLayout.createSequentialGroup()
                .addComponent(dynamicInput, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(config, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(output, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(config, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(output, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void arrivalTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrivalTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrivalTimeActionPerformed

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        // TODO add your handling code here:
        try{
            String pName = processName.getText();
            int aTime = Integer.parseInt(arrivalTime.getText());
            int bTime = Integer.parseInt(burstTime.getText());
            
            ProcessControlBlock p = new ProcessControlBlock(
                    pName,
                    aTime,
                    bTime
            );
            
            hold.enqueue(p);
            
            processName.setText("");
            arrivalTime.setText("");
            burstTime.setText("");
            
            tableModel.addRow(new Object[]{
                pName,
                aTime,
                bTime
            });
            
            JLabel title = new JLabel();
            title.setText("Input List");
            title.setFont(new Font("Arial", Font.BOLD, 20));
            
            JPanel dynamicInput = new JPanel();
            dynamicInput.setLayout(new BorderLayout());
            
            dynamicInput.add(
                    title,
                    BorderLayout.NORTH
            );
            
            dynamicInput.add(
                    new JScrollPane(tableForInput),
                    BorderLayout.CENTER
            );
            
            input.removeAll();

            input.setLayout(new BorderLayout());

            input.add(
                    new JScrollPane(dynamicInput),
                    BorderLayout.CENTER
            );
            
            Dimension currentSize = input.getSize();

            input.setPreferredSize(currentSize);

            input.revalidate();
            input.repaint();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter a valid input!");
        }
    }//GEN-LAST:event_insertActionPerformed
// =============================================================================================================================
    private JTable createTable(FinishedQueue finishedProcesses, boolean isRR){
        if(isRR){
            String[] columns = {
                "Process Name",
                "Arrival Time",
                "Burst Time",
                "Completion Time",
                "Turn Around Time",
                "Waiting Time"
            };

            DefaultTableModel model = new DefaultTableModel(columns, 0);
            JTable table = new JTable(model);

            int numProcess = finishedProcesses.getSize();
            for(int i=0; i<numProcess; i++){
                ProcessControlBlock process = finishedProcesses.dequeue();

                model.addRow(new Object[]{
                    process.getProcessName(),
                    process.getArrivalTime(),
                    process.getBurstTime(),
                    process.getCompletionTime(),
                    process.getTurnAroundTime(),
                    process.getWaitingTime()
                });

                finishedProcesses.enqueue(process);
            }
            
            return table;
        }
        
        String[] columns = {
            "Process Name",
            "Arrival Time",
            "Burst Time",
            "Start Time",
            "Waiting Time"
        };

        DefaultTableModel model = new DefaultTableModel(columns, 0);
        JTable table = new JTable(model);

        int numProcess = finishedProcesses.getSize();
        for(int i=0; i<numProcess; i++){
            ProcessControlBlock process = finishedProcesses.dequeue();

            model.addRow(new Object[]{
                process.getProcessName(),
                process.getArrivalTime(),
                process.getBurstTime(),
                process.getStartTime(),
                process.getWaitingTime()
            });

            finishedProcesses.enqueue(process);
        }
        
        return table;
    }
    
    private JLabel createTitle(String title, int size){
        JLabel method = new JLabel();
        method.setText(title);
        method.setFont(new Font("Arial", Font.BOLD, size));
        
        return method;
    }
    
    private JPanel createGanttPanel(GanttChart[] ganttChart){
        JPanel ganttPanel = new JPanel(new GridLayout(1, 0));
        for(GanttChart entry : ganttChart){
            if (entry == null) {
                break;
            }

            JLabel cell = new JLabel(
                    entry.getProcessName(),
                    SwingConstants.CENTER
            );
            cell.setBorder(
                    BorderFactory.createLineBorder(Color.BLACK)
            );

            ganttPanel.add(cell);
        }
        
        return ganttPanel;
    }
    
    private JPanel createTimePanel(GanttChart[] ganttChart){
        JPanel timePanel = new JPanel(new GridLayout(1, 0));

        JLabel startLabel = new JLabel(
                String.valueOf(ganttChart[0].getStartTime()),
                SwingConstants.LEFT
        );

        timePanel.add(startLabel);
        
        for(int i=0; i<ganttChart.length; i++){
            GanttChart entry = ganttChart[i];
            
            if(entry == null){
                break;
            }
            
            JLabel timeLabel;
            if(ganttChart[i+1] == null){
                timeLabel = new JLabel(
                    String.valueOf(entry.getCompletionTime()),
                    SwingConstants.RIGHT
                );
            }else{
                timeLabel = new JLabel(
                    String.valueOf(entry.getCompletionTime()),
                    SwingConstants.CENTER
                );
            }

            timePanel.add(timeLabel);
        }
        
        return timePanel;
    }
    
    private JPanel createOutputListPanel(JLabel ol, JTable table){
        JPanel outputListPanel = new JPanel(new BorderLayout());
        
        outputListPanel.add(
                ol,
                BorderLayout.NORTH
        );

        outputListPanel.add(
                new JScrollPane(table),
                BorderLayout.SOUTH
        );
        
        return outputListPanel;
    }
    
    private JPanel createDynamicOutput(JLabel method, JPanel outputListPanel, JPanel chartPanel){
        JPanel dynamicOutput = new JPanel();
        dynamicOutput.setLayout(new BorderLayout());
        
        dynamicOutput.add(
                method,
                BorderLayout.NORTH
        );
        
        
        dynamicOutput.add(
                outputListPanel,
                BorderLayout.SOUTH
        );
        
        dynamicOutput.add(
                chartPanel,
                BorderLayout.CENTER
        );
        
        return dynamicOutput;
    }
    
    private JPanel createChartPanel(JLabel gc, JPanel ganttPanel, JPanel timePanel){
        JPanel chartPanel = new JPanel(new BorderLayout());
        chartPanel.add(
                gc,
                BorderLayout.NORTH
        );
        
        chartPanel.add(new JScrollPane(
                        ganttPanel,
                        JScrollPane.VERTICAL_SCROLLBAR_NEVER,
                        JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED
                ),
                BorderLayout.CENTER
        );
        
        chartPanel.add(new JScrollPane(
                        timePanel,
                        JScrollPane.VERTICAL_SCROLLBAR_NEVER,
                        JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED
                ),
                BorderLayout.SOUTH
        );
        return chartPanel;
    }
//=========================================================================================================================
    
    private void fcfsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcfsbtnActionPerformed
        // TODO add your handling code here:
        if(hold.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter processes first!");
            return;
        }
        fcfs = new FirstComeFirstServed();
        fcfs.schedule(hold);

        FinishedQueue finishedProcesses = fcfs.getFinishedProcesses();
        GanttChart[] ganttChart = fcfs.getGanttChart();

        JLabel method = createTitle("First Come First Served", 20);
        
        JLabel ol = createTitle("Output Table", 18);
        JTable table = createTable(finishedProcesses, false);
        JPanel outputListPanel = createOutputListPanel(ol, table);

        JLabel gc = createTitle("Gantt Chart", 18);
        JPanel ganttPanel = createGanttPanel(ganttChart);
        JPanel timePanel = createTimePanel(ganttChart);
        JPanel chartPanel = createChartPanel(gc, ganttPanel, timePanel);
        
        JPanel dynamicOutput = createDynamicOutput(method, outputListPanel, chartPanel);
       
        JPanel metrics = new JPanel(new BorderLayout());
        JLabel metricsLabel = createTitle("Mertrics", 18);
        JLabel measurements = createTitle("Average waiting time: " + fcfs.getAverageWaitingTime(), 14);
        
        metrics.add(metricsLabel, BorderLayout.NORTH);
        metrics.add(measurements, BorderLayout.CENTER);
        
        addToOutput(dynamicOutput, metrics);
    }//GEN-LAST:event_fcfsbtnActionPerformed

    private void sjnbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sjnbtnActionPerformed
        // TODO add your handling code here:
        if(hold.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter processes first!");
            return;
        }
        sjn = new ShortestJobNext();
        sjn.schedule(hold);
        
        FinishedQueue finishedProcesses = sjn.getFinishedProcesses();
        GanttChart[] ganttChart = sjn.getGanttChart();

        JLabel method = createTitle("Shortest Job Next", 20);
        
        JLabel ol = createTitle("Output Table", 18);
        JTable table = createTable(finishedProcesses, false);
        JPanel outputListPanel = createOutputListPanel(ol, table);

        JLabel gc = createTitle("Gantt Chart", 18);
        JPanel ganttPanel = createGanttPanel(ganttChart);
        JPanel timePanel = createTimePanel(ganttChart);
        JPanel chartPanel = createChartPanel(gc, ganttPanel, timePanel);
        
        
        JPanel dynamicOutput = createDynamicOutput(method, outputListPanel, chartPanel);
        
        JPanel metrics = new JPanel(new BorderLayout());
        JLabel metricsLabel = createTitle("Mertrics", 18);
        JLabel measurements = createTitle("Average waiting time: " + sjn.getAverageWaitingTime(), 14);
        
        metrics.add(metricsLabel, BorderLayout.NORTH);
        metrics.add(measurements, BorderLayout.CENTER);
        
        addToOutput(dynamicOutput, metrics);
    }//GEN-LAST:event_sjnbtnActionPerformed

    private void rrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rrbtnActionPerformed
        // TODO add your handling code here:
        if(hold.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter processes first!");
            return;
        }
        try{
            int tq = Integer.parseInt(JOptionPane.showInputDialog("Enter time quantum: "));
            rr = new RoundRobin(tq);
            rr.schedule(hold);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter a valid time quantum!");
        }


        FinishedQueue finishedProcesses = rr.getFinishedProcesses();
        GanttChart[] ganttChart = rr.getGanttChart();



        JLabel method = createTitle("Round Robin", 20);

        JLabel ol = createTitle("Output Table", 18);
        JTable table = createTable(finishedProcesses, true);
        JPanel outputListPanel = createOutputListPanel(ol, table);

        JLabel gc = createTitle("Gantt Chart", 18);
        JPanel ganttPanel = createGanttPanel(ganttChart);
        JPanel timePanel = createTimePanel(ganttChart);
        JPanel chartPanel = createChartPanel(gc, ganttPanel, timePanel);

        JPanel dynamicOutput = createDynamicOutput(method, outputListPanel, chartPanel);


        JPanel metrics = new JPanel(new BorderLayout());
        JLabel metricsLabel = createTitle("Mertrics", 18);
        JLabel awt = createTitle("Average waiting time: " + rr.getAverageWaitingTime(), 14);
        JLabel att = createTitle("Average turn around time: " + rr.getAverageTurnAroundTime(), 14);
        JLabel timeQuantum = createTitle("Time quantum: " + rr.getTimeQuantum(), 14);
        
        JPanel measurements = new JPanel(new BorderLayout());
        measurements.add(awt, BorderLayout.NORTH);
        measurements.add(att, BorderLayout.CENTER);

        metrics.add(metricsLabel, BorderLayout.NORTH);
        metrics.add(measurements, BorderLayout.CENTER);
        metrics.add(timeQuantum, BorderLayout.SOUTH);

        addToOutput(dynamicOutput, metrics);
        
    }//GEN-LAST:event_rrbtnActionPerformed

    private void addToOutput(JPanel dynamicOutput, JPanel metrics){
        Dimension currentSize = output.getSize();

        output.setPreferredSize(currentSize);

        output.removeAll();

        output.setLayout(new BorderLayout());

        output.add(
                new JScrollPane(dynamicOutput),
                BorderLayout.CENTER
        );
        
        output.add(
                metrics,
                BorderLayout.SOUTH
        );

        output.revalidate();
        output.repaint();
    }
    
    private void restartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartActionPerformed

        // TODO add your handling code here:
        while(!hold.isEmpty()){
            hold.dequeue();
        }
        
        Dimension currentSize1 = input.getSize();
        input.setPreferredSize(currentSize1);
        
        input.removeAll();
        input.revalidate();
        input.repaint();
        
        tableModel.setRowCount(0);
        
        Dimension currentSize2 = output.getSize();
        output.setPreferredSize(currentSize2);
        
        output.removeAll();
        output.revalidate();
        output.repaint();
    }//GEN-LAST:event_restartActionPerformed

    private void terminateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminateActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Thank you for using our program. Goodbye!");
        System.exit(0);
    }//GEN-LAST:event_terminateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arrivalTime;
    private javax.swing.JTextField burstTime;
    private javax.swing.JPanel config;
    private javax.swing.JScrollPane dynamicInput;
    private javax.swing.JScrollPane dynamicOutput;
    private javax.swing.JButton fcfsbtn;
    private javax.swing.JPanel input;
    private javax.swing.JButton insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel output;
    private javax.swing.JTextField processName;
    private javax.swing.JButton restart;
    private javax.swing.JButton rrbtn;
    private javax.swing.JButton sjnbtn;
    private javax.swing.JButton terminate;
    // End of variables declaration//GEN-END:variables
}
